import type { IChatMessage } from "../../types";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import rehypeRaw from "rehype-raw";
import rehypeSanitize from "rehype-sanitize";
import {User,Bot} from "lucide-react";


interface ChatMessageBubbleProps {
  message: IChatMessage;
}

const ChatMessageBubble = ( { message }: ChatMessageBubbleProps) => {
  const isUser = message.role === "user";
  const isSystem = message.role === "system"; //this is for the use case of pinning the summary generated by the first source uploaded<ai gen summary ofcourse>

  return (
    <> 
     <div className={`flex gap-3 mb-4 ${isUser ? 'justify-end' : 'justify-start'}`}>
      {!isUser && !isSystem && (
        <div className="w-21 p-0.4 h-full  flex items-center justify-center flex-shrink-0 shawdow-sm">
          <Bot size={20} className="text-blue-300"/>
          <h2 className="p-0.5 text-sm text-text-sec">{message.role}</h2>
        </div>
      )}
      <div className={`min-w-xs lg:max-w-md xl:max-w-lg  p-2 rounded-2xl shadow-sm
         ${isSystem ? 
        'bg-blue-50 text-gray-700 border border-blue-200 text-xs italic' : isUser ?
        'bg-blue-600 text-white' : 'bg-bg-sec text-text-pri'}`} >
          
        <ReactMarkdown
        remarkPlugins={[remarkGfm]}
        rehypePlugins={[rehypeRaw,rehypeSanitize]}
        components={{
          p:({children})=><p className="text-sm m-0.1 p-1 leading-relaxed whitespace-pre-wrap break-words">{children}</p>,
          li:({children})=><li className="ml-4 list-disc">{children}</li>,
          code: ({ children }) => (
          <code className="bg-bg-sec text-sm px-1 rounded font-mono">{children}</code>
             ),
          strong:({children})=>(<strong className="font-semibold">{children}</strong>),
          em:({children})=>(<em className="italic">{children}</em>),
        }}>
        {message.message}
        </ReactMarkdown>
         </div>
         
         {isUser && (
          <div className="max-w-xs h-full flex items-center justify-center flex-shrink-0 shadow-sm">
            <User size={20} className="text-green-400"/>
            </div>
         )}
     </div>

    </>
)
};

export default ChatMessageBubble;

