import type { IChatMessage } from "../../types";
import ReactMarkdown from "react-markdown";
import {User,Bot} from "lucide-react";

interface ChatMessageBubbleProps {
  message: IChatMessage;
}

const ChatMessageBubble = ( { message }: ChatMessageBubbleProps) => {
  const isUser = message.role === "user";
  const isSystem = message.role === "system"; //this is for the use case of pinning the summary generated by the first source uploaded<ai gen summary ofcourse>

  return (
    <> 
     <div className={`flex gap-3 mb-4 ${isUser ? 'justify-end' : 'justify-start'}`}>
      {!isUser && !isSystem && (
        <div className="w-21 p-0.4 h-full  flex items-center justify-center flex-shrink-0 shawdow-sm">
          <Bot size={20} className="text-blue-300"/>
          <h2 className="p-0.5 text-sm text-gray-800">{message.role}</h2>
        </div>
      )}
      <div className={`min-w-xs lg:max-w-md xl:max-w-lg  py-3 rounded-2xl shadow-sm ${isSystem ? 'bg-blue-50 text-gray-700 border border-blue-200 text-xs italic' : isUser ? 'bg-blue-600 text-white' : 'bg-gray-100 text-gray-900'}`}>
        <p className="text-sm m-0.1 p-1 leading-relaxed whitespace-pre-wrap break-words">{message.message}</p>
         </div>

         {isUser && (
          <div className="max-w-xs h-full flex items-center justify-center flex-shrink-0 shadow-sm">
            <User size={20} className="text-green-400"/>
            </div>
         )}
     </div>

    </>
)
};

export default ChatMessageBubble;

