spring.application.name=MindSpace

# Database Configuration
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:postgres}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Static Content (Audio)
spring.web.resources.static-locations=file:audio/
spring.mvc.static-path-pattern=/audio/**

# Security & AI
gemini.api.key=${GEMINI_API_KEY}
application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=86400000
